language: php

php:
  - 5.3

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - mysql -e "CREATE DATABSE IF NOT EXISTS queryer_tests;" -uroot;

script:
  - phpunit --configuration phpunit.xml
  - phpunit --configuration phpunit.mysql.xml

notifications:
    on_success: change
    on_failure: always