language: php

php:
  - 5.3

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit --configuration phpunit.xml

notifications:
    on_success: never
    on_failure: always