<?php
namespace Queryer\Engine\Mysql;

/**
 * Class MysqliInterface
 * @package Queryer\Engine\Mysql
 */
abstract class MysqliInterface
{
    /**
     * The affected rows by the latest query.
     * @var int
     */
    public $affected_rows;

    /**
     * The insert ID generated by the latest query.
     * @var int
     */
    public $insert_id;

    /**
     * The error of the last query.
     * @var int
     */
    public $errno;

    /**
     * The error of the last query.
     * @var string
     */
    public $error;

    /**
     * Sets the options for connecting to the database.
     *
     * @param array $options
     * @return void
     */
    public abstract function setOptions(array $options);

    /**
     * Executes the query against the database.
     *
     * @param string $query
     * @return mixed
     */
    public abstract function query($query);

    /**
     * Escapes the string for safe insertion into a query.
     *
     * @param string $str
     * @return mixed
     */
    public abstract function real_escape_string($str);
} 